### ISSUE TITLE
Illandril's Hotbar Uses compatibility issue

### ISSUE THREAD

**Issue by NutritiousCookie** [Xbozon/rpg-styled-ui#10]
[Illandril's Hotbar Uses](https://github.com/illandril/FoundryVTT-hotbar-uses) floats beneath your CSS. I'm currently hacking it by giving the uses element a z-index of 100, but a more permanent solution would be nice.
![image](https://user-images.githubusercontent.com/30578022/135083127-73efe725-01f2-47ea-b134-09a6b00dccdf.png) <- with RPG UI
![image](https://user-images.githubusercontent.com/30578022/135083185-1ebbee99-c657-4162-b313-fd20c02d8ea0.png) <- without RPG UI

**Comment by Xbozon** [comment]
@NutritiousCookie The problem is clear, I will add a fix in the next patch v0.4.1.

**Comment by Xbozon** [comment]
@NutritiousCookie 
I checked on the current version, the panel is displayed:
![image](https://user-images.githubusercontent.com/5074477/135157536-af6fe6a3-e226-4ff4-b1e8-a885fad27e32.png)

I've fixed this before (https://github.com/Xbozon/rpg-styled-ui/issues/6), maybe installed not the latest version? Also maybe there is another problem, but which one?

**Comment by NutritiousCookie** [comment]
Somehow I was on version 3.0, despite having downloaded it for the first time yesterday, and 3.0 being 2 1/2 months out of date.

¯\_(ツ)_/¯

Thanks for the fix.

**Comment by Xbozon** [comment]
@NutritiousCookie 
Most likely you downloaded via install module and search among all the modules. I forgot to add the new version to the foundry hub. Fixed that too :)
