### ISSUE TITLE
Compatibility with Alternative Pause Icon

### ISSUE THREAD

**Issue by mfozz** [Xbozon/rpg-styled-ui#100]
I'd like to be able to use Alternative Pause Icon at the same time or have an option in RPG Styled UI to change the pause icon. The module currently overrides or prevents Alternative Pause Icon from working.

**Comment by Akexis** [comment]
I'm having the same issue. Your module is awesome! So I'll put up with the pause icon if needed, but it would be nice to either control it with Alternative Pause Icon - which I've been doing - or have a way to change it in your module. All the same, thanks for the hard work.

**Comment by Xbozon** [comment]
It will definitely be fixed, I'd like to believe this week

**Comment by Xbozon** [comment]
Fixed in v1.2.1, please try!
