### ISSUE TITLE
Combat Carousel Button

### ISSUE THREAD

**Issue by thedigitaldungeonmaster** [Xbozon/rpg-styled-ui#13]
Love the UI! Just a quick bug to report. The Combat Carousel button in the sidebar is white rather than the greyish yellow color of all the other buttons. The backround of the button is fine, but the actual CC icon is white. Doesn't break anything, but thought I'd report it all the same. Thanks for this amazing release!

**Comment by Xbozon** [comment]
@thedigitaldungeonmaster 
Fixed in v0.4.1. This is the only icon as an image, not a font icon, it was hard to fix it right away and I forgot about it :D

Feel free to write about the little things if they bother you!
