### ISSUE TITLE
Compact Mode Logo 

### ISSUE THREAD

**Issue by Jmwhite45** [Xbozon/rpg-styled-ui#15]
While in compact mode, the foundry logo is still visible and is drawn above buttons

![image](https://user-images.githubusercontent.com/8539781/135186939-0d74982f-0ae4-4508-a35e-10e1eba9146a.png)

![image](https://user-images.githubusercontent.com/8539781/135186973-21b91ef7-79e7-4813-89e4-b8b18bc1ffa6.png)
^here are my current settings for reference

versions:
foundry 0.8.9
DnD5e: 1.4.3
RPG styled UI: 0.4.0

**Comment by Xbozon** [comment]
@Jmwhite45 Upgrade to v0.4.1. Should be fixed.

**Comment by InnilToo** [comment]
Can confirm it works.
Thanks to testing I've found this https://github.com/Xbozon/rpg-styled-ui/issues/16

**Comment by Xbozon** [comment]
Closing. If you still have the problem, reopen the issue!
