### ISSUE TITLE
Changing settings is quirky

### ISSUE THREAD

**Issue by InnilToo** [Xbozon/rpg-styled-ui#16]
When I want to toggle on/off some features only one change per save is registered. What I mean byt this:
Start position:
![image](https://user-images.githubusercontent.com/33260912/135316055-1d288b98-4b84-4d36-b8a7-785ede825c7a.png)
Change to and hit Save Changes:
![image](https://user-images.githubusercontent.com/33260912/135316120-0b46e7ff-99f2-4930-8211-b63ad9724f32.png)
Outcome:
![image](https://user-images.githubusercontent.com/33260912/135316163-ccc034d3-f0c2-4d4d-b622-20dc0a5f5430.png)

FVTT 0.8.9
DnD5e 1.4.3
RPG Styled UI 0.4.1

**Comment by Xbozon** [comment]
@InnilToo 
I checked, there is a real problem. However, I use the standard foundry api to generate the settings, almost no control over its behavior. I will find out more about it over the weekend.
