### ISSUE TITLE
Secret/Blind/Whisper Chat Colors

### ISSUE THREAD

**Issue by NutritiousCookie** [Xbozon/rpg-styled-ui#17]
In base Foundry, different types of messages have slightly differently colored text/borders/background, to give a visual indication of who can read it.
I would love to still have this functionality in RPG UI.

![image](https://user-images.githubusercontent.com/30578022/135500598-cc3c86d6-1379-4df9-ba85-9bbc3dbad1f9.png)
![image](https://user-images.githubusercontent.com/30578022/135501456-d2073c1d-e037-42de-91b4-9c11b798c3dd.png)

**Comment by Xbozon** [comment]
@NutritiousCookie 

I was planning to do that. It's not used in the games whats I run, but I'll try to do it sooner now. Thanks for your feedback!

**Comment by Xbozon** [comment]
@NutritiousCookie 
Added small differences in v0.4.5. Not perfect, but I will try in future games and improve.

![image](https://user-images.githubusercontent.com/5074477/136662230-70d6a450-72e8-4db1-a473-80765e2d9899.png)
