### ISSUE TITLE
Suggested Feature - On/Off Toggle

### ISSUE THREAD

**Issue by thedigitaldungeonmaster** [Xbozon/rpg-styled-ui#18]
Good day. I'm loving this module and had a suggestion for its future development based on some of my player feedback. 

4 of my 5 players love the UI and the feel it gives to Foundry.  It had a huuuge splash at our last session. Unfortunately, that 1 player that doesn't love the UI has problems with their vision, and the colors and sizing of the UI make it difficult for that player to read everything on the screen. Because of this, I will likely need to stop the use of the UI for that campaign. 

My suggestion would be to have a toggle in the settings where the Players can choose to turn the UI on or off. Providing that level of choice to each user would be incredible. Right now, if I turn the module on, every user is forced to use the UI, so in a situation where even a single player has an issue w/ the interface, I have to turn it off for everyone. 

I'm not a dev and have no idea how much work would go into that. Just thought I'd suggest this as a feature for future development. It would allow GMs with users with various vision disabilities to still let their other players enjoy your incredible work.

**Comment by Xbozon** [comment]
@thedigitaldungeonmaster 
Thank you so much for your feedback.Usually enhancements come last in priority, but I understand your problem and will do it as quickly as I can so that everyone can enjoy the game.

**Comment by Xbozon** [comment]
@thedigitaldungeonmaster 
Done, please check that everything works fine.
