### ISSUE TITLE
[Not an issue per se] Horizontal scene navigation

### ISSUE THREAD

**Issue by struckyCZ** [Xbozon/rpg-styled-ui#2]
Hey, the UI looks super cool. I think it's gonna fit the Curse of Strahd game I'm going to be running in a few months. I just hate the vertical UI. Could you, please, at least make some setting where we could choose how we want it? Honestly it's the only thing that's potentially keeping me from going with the UI in the CoS.

**Comment by Xbozon** [comment]
This was done because of the conflict with Combat Carousel. I can make a customization, but the navigation will be on top of Combat Carousel if you use it ;(

**Comment by struckyCZ** [comment]
I personally don't use the Combat Carousel so I won't mind at all. Just feeling a little weird to be the only person you're gonna be making the change for (or at least the only vocal person). :-D

**Comment by Xbozon** [comment]
I don't like the vertical solution too, but it was a compromise. I'll try to fix it.

**Comment by Xbozon** [comment]
@struckyCZ 

Done. Please enjoy!

Thanks for using my module. Email me if anything still doesn't work right.

**Comment by struckyCZ** [comment]
@Xbozon thanks a lot mate!
