### ISSUE TITLE
Feature Request - Toggle Chat Box Background

### ISSUE THREAD

**Issue by Heljspe** [Xbozon/rpg-styled-ui#20]
Hi, 
This module is SUPER cool! Love the feel it gives the game. :D 
We'd love to keep pretty much all of it, expect the part that changes the chat background to black (which has made reading some of the rolls hard. 
Would it be possible to have a toggle (maybe at the player level) that turns the mod on/off _just for the chat log?_
(or maybe an option for parchment background instead of black?)
With so many mod integrations, it might be easier to just toggle the chat log than have compatibility with every mod that outputs to chat. :p 

(example of a player rolling externally from dndbeyond)
![image](https://user-images.githubusercontent.com/68180128/135751464-870d4c1d-d6d9-4454-a068-3130b4ee545b.png)

**Comment by Xbozon** [comment]
@Heljspe 
I'm going to try to change the texture to a lighter one. It will take time.

**Comment by Xbozon** [comment]
@Heljspe 

Unfortunately, despite several attempts, it failed to make the light chat compatible with the overall dark design. All of the options looked incredibly bad.

As an alternative, I can only add the necessary plugin support.
