### ISSUE TITLE
Problem with DAE

### ISSUE THREAD

**Issue by Argonaut13** [Xbozon/rpg-styled-ui#21]
So, the ui completely f*cks DAE active affects window. Since DAE is one of the biggest mods for Foundry, that's kind of a deal breaker XD Hope this gets fixed as the ui is gorgeous and its a shame not to be able to use it!
![The Darkness Consumes](https://user-images.githubusercontent.com/24908933/135831994-d7c852ec-b4ae-4c18-9e15-1bee251a3080.jpg)

**Comment by Xbozon** [comment]
@Argonaut13 
What kind of character sheet are you using?

**Comment by InnilToo** [comment]
I do believe this is https://github.com/sdenec/tidy5e-sheet as I have the same issue. Looks same in light and dark mode.

**Comment by Xbozon** [comment]
@InnilToo Thanks for the answer, I will exclude the use of styles for DAE.

**Comment by Xbozon** [comment]
@Argonaut13 
I installed both mods, went into effects editing, but did not saw a problem. Can you write the foundry core version, the version of the mods and where exactly the problem is located, thanks!

**Comment by Argonaut13** [comment]
> @Argonaut13 I installed both mods, went into effects editing, but did not saw a problem. Can you write the foundry core version, the version of the mods and where exactly the problem is located, thanks!

Even with everything disabled except for DAE and the UI+Journal Styling it does it. all my modules are up to date as of this post, as is my core version and ruleset
![Bug](https://user-images.githubusercontent.com/24908933/136741190-836d662f-f4b5-4d06-ad2d-5b7fa14ba29e.jpg)

**Comment by rjbprime** [comment]
Hello, this seems to be an Issue again. Using FoundryVTT 11.315, DND5e 3.1.2, and the current DAE that is compatible with DND5e 3.1.2, [11.3.19](https://gitlab.com/tposney/dae/-/commit/d5915ecd2af2e143dd81c582a240ed5d403ebce4). Can this be reopened and reproduced on your end?

Kind regards.
