### ISSUE TITLE
Clash with Alternative Pause Icon

### ISSUE THREAD

**Issue by dutchcolonial** [Xbozon/rpg-styled-ui#26]
I noticed that the pause icon is changed when activation this module. In itself fine, though it seems to clash with another module called Alternative Pause Icon. If I select another icon in Alternative Pause Icon, I get a messed up pause icon
![image](https://user-images.githubusercontent.com/69436083/137764578-71eff672-add0-42c3-9415-e830b7fb377b.png)

Not sure if it is this module or the other module that is causing the issue.

**Comment by Xbozon** [comment]
@dutchcolonial fixed in 0.6.1
