### ISSUE TITLE
[Styling Bug] Right menu panel slides a bit down 

### ISSUE THREAD

**Issue by tagnullde** [Xbozon/rpg-styled-ui#30]
Once the module is active. The sidepanel slides down a bit.
I hope it comes across on the following screenshots.

Here you can see, the buttons almost touch the browser UI.
![grafik](https://user-images.githubusercontent.com/44159008/138817695-209c8637-e345-4351-8696-8a4d359a8610.png)

Here you can see a noticiable gap between the buttons and the browser UI
![grafik](https://user-images.githubusercontent.com/44159008/138817880-7049ab0a-f017-4b28-83a6-b8c2f87e61a1.png)

I understand that the background graphic needs some space, but maybe it can be optimized a bit. If you think it's fine.
Just close this issue. ;)

Regards
x41

**Comment by Xbozon** [comment]
@tagnullde 
Raised it 10px higher. Tried larger, but it loses the feeling of a jagged design.
