### ISSUE TITLE
[Feature] Theme Presets

### ISSUE THREAD

**Issue by KonteiKeisei** [Xbozon/rpg-styled-ui#31]
I would love to see a drop down with different theme/color options.

I attempted to make a custom version of this with a blue/parchment feel for a nautical campaign i am running, but it somehow pulls the red and black regardless of the converted/changed UI elements in mine.

Figured, you actually know what your doing, would be cool to have some options depending on the style of campaign being run!

**Comment by Xbozon** [comment]
@KonteiKeisei 

The main problem is that I use a large set of pre-made textures in red-brown colors, it is difficult to paint them through css. I have thoughts to convert all textures to black and modify them at startup. Unfortunately, based on the amount of work, I won't be able to take on this until 2-3 months at the earliest

:(

**Comment by KonteiKeisei** [comment]
> 
> 
> @KonteiKeisei
> 
> The main problem is that I use a large set of pre-made textures in red-brown colors, it is difficult to paint them through css. I have thoughts to convert all textures to black and modify them at startup. Unfortunately, based on the amount of work, I won't be able to take on this until 2-3 months at the earliest
> 
> :(

Do you mean the ones in the UI folder? or are you pulling from another place and it overrides those. I have already done a test run of some blue if you want me to send them your way? Though the black thing you mentioned, and coloring things using the CSS sounds cleaner for sure.

**Comment by Xbozon** [comment]
@KonteiKeisei 
I would be happy to see a screenshot of what it looks like for you :)

I'm definitely not going to do through a lot of image sets, it would add a lot of workload, especially if more color variations are needed.

But I'm interested to see what yours looks like)

**Comment by KonteiKeisei** [comment]
It looks stock, that was the issue, i have all the image files done in blue as a test and nothing happened, but then again, i have no idea what i'm doing! No worries, i don't want to add to your workload my dude.

**Comment by Xbozon** [comment]
@KonteiKeisei If you have changed the images and nothing applies, you usually need a complete reboot of foundry for the changes to apply. You can also try refreshing the page forcefully by resetting the images saved by your browser.

I'll keep this open and come back to it when I can.

**Comment by KonteiKeisei** [comment]
I have a quick and dirty Blue (nautical) version of this running. Are we good to fork this so that I can work with a friend of mine to develop a built in dropdown for switching themes?

![image](https://user-images.githubusercontent.com/49371326/187541494-ca0e1dd3-4306-4cdc-9a2f-afd8288f626e.png)

**Comment by Xbozon** [comment]
@KonteiKeisei 

I think the best solution would be to release an add-on that adds another css file and textures. I don't mind the fork, but it would be hard to maintain updates.

If you need help with how to make an add-on, I can help.
