### ISSUE TITLE
Two issue and one request. :)

### ISSUE THREAD

**Issue by Padhiver** [Xbozon/rpg-styled-ui#32]
Hello !

Already thank you for this UI which I think is beautiful, it is perfect for fantasy and travel in Middle Earth. :D

I post below two small problems that I encounter, the first one comes from Midi Qol, more precisely the application map and damage calculation in the chat: 
![image](https://user-images.githubusercontent.com/80126915/141760125-c9cb37d9-d398-4c52-95c9-a5fd04423ee3.png)

As you can see, you can't see the chosen option very well, except when clicking on it: 
![image](https://user-images.githubusercontent.com/80126915/141760260-b271aa68-5ebc-4d6f-8b49-1711d64e8803.png)

So much for the first problem. The second one is from the compendium, the sidebar that allows you to climb up and down has become all black: 
![image](https://user-images.githubusercontent.com/80126915/141760401-d4696c54-a074-446e-bfae-4e3699407a85.png)

And it doesn't matter where you are in the compendium, there is no more location marker.

And the small request now, it turns out that the "links" in the articles are a little too white (image below), and I would like to make tests of colour to perhaps make them a little more black at home but I do not know much about it, would it be possible to know the line to modify to make these tests? I'd like to do some colour tests to make them a bit blacker at home but I don't know much about it.

![image](https://user-images.githubusercontent.com/80126915/141760781-27208342-1d38-473e-b80e-dd823fb6ad1d.png)

Thanks for reading! :)

**Comment by Xbozon** [comment]
@DarkyMago 

The first two problems I understand, I think I can fix in the next patch. As for the links and chat commands, I fixed it earlier (https://github.com/Xbozon/rpg-styled-ui/issues/22), it's strange that this problem exist. Where are you using them?

**Comment by Padhiver** [comment]
In a note you don't have this problem, but in a weapon or an ability you do, as well as in a class table for example. Here a screenshot : 
![image](https://user-images.githubusercontent.com/80126915/141825547-77b8baaa-3d46-433d-9548-c974bf8be2d1.png)

I use Dnd5e and latest version of everything, 8.9 Foundry. And looking at the issue you posted it is indeed the same problem! I tested with a blank world and just with RPG UI, it does the same thing. 😃 

(English are not my native langage, i hope i'm clear enough ! :)

**Comment by Xbozon** [comment]
@Padhiver 
Don't worry, English is not my native language either. I understand now, thank you. The previous fix only affects the chat.

**Comment by Xbozon** [comment]
@Padhiver 
Can you send me your Midi settings (as screenshots)? I can't get the same chat message :D. Thank you!

**Comment by Padhiver** [comment]
Sure ! 

In english, you have to go in "Workflow Setting" (where my mouse are) : 
![image](https://user-images.githubusercontent.com/80126915/141833709-3bf3db59-b9ed-4797-9cfb-394f2e359751.png)

Then, in Workflow tab, scroll all the way down and it's in "Damage" section, auto apply damage + card chat. :)
![image](https://user-images.githubusercontent.com/80126915/141833845-75fd02e5-ed7d-4abf-820a-032c51a40487.png)

**Comment by Xbozon** [comment]
@Padhiver 
Thanks for the quick answers, fixed in v0.6.4. Let me know if there are any problems.

**Comment by Padhiver** [comment]
Thank you so much ! It's perfect. The three problems are all solved. :D
