### ISSUE TITLE
Module not v9 compatible

### ISSUE THREAD

**Issue by tagnullde** [Xbozon/rpg-styled-ui#33]
You probably know but here it is anyway.
The module breaks CSS in v9.

![image](https://user-images.githubusercontent.com/44159008/147211693-b0bfd8c3-da2b-47f1-b206-76e702167c11.png)

As you can see, the right handside menu CSS is repeated over the complete canvas. 

Have a nice holiday.

**Comment by Xbozon** [comment]
@tagnullde 
There are, in reality, a lot more problems to solve. I'm working on version 9, most likely to be released next week.

**Comment by Xbozon** [comment]
@tagnullde 
I added compatibility in v0.7.0, try it!

**Comment by tagnullde** [comment]
Seems to work :)
Thanks mate.

**Comment by Xbozon** [comment]
@tagnullde 
Thank you for using the mod :)
