### ISSUE TITLE
No DnD 5e integration

### ISSUE THREAD

**Issue by Kawooom** [Xbozon/rpg-styled-ui#34]
would it be possible to make a version without the D'n'D 5e features pls so people could use it with other game systems?

**Comment by Xbozon** [comment]
@Kawooom 

Specifying a particular system obligates me to provide support by fixing bugs and inaccuracies. You can manually download the archive with the mod and remove these lines in the file module.json. 
```
"systems": ["dnd5e", "pf2e"],
```

Then it will work with any system. What system are you using?

**Comment by Kawooom** [comment]
i made my homebrew system using sandbox. thx for helping me
