### ISSUE TITLE
Placement of "Use Crit Damage" popup

### ISSUE THREAD

**Issue by tagnullde** [Xbozon/rpg-styled-ui#35]
Hey there,

is there a way for you to place the "Use Crit Damage" popup somewhere more "centered"?
I had it multiple times now, that I was wondering why I couldn't apply the damage until I noticed this small little popup way out of my sight. :D 

![image](https://user-images.githubusercontent.com/44159008/147781347-49bb837f-9315-458f-81ac-4744af1bfb74.png)

If not. No worries. I'll probably will get used to it at some point in the distant future. ^^

**Comment by Xbozon** [comment]
@tagnullde 
I'm not quite sure if this is a problem with the rpg-style module. What modules do you have installed?

**Comment by tagnullde** [comment]
You closed the issue. Do you still need the list of modules?

**Comment by Xbozon** [comment]
I must have accidentally clicked, yes, the list of modules is still needed

**Comment by Sasmira** [comment]
> 

is it better roll module ?

**Comment by tagnullde** [comment]
Active Modules:
----------
Active Effects to Chat v;
Babele v;
Better Rolls for 5e v;
Changelogs & Conflicts v;
Compendium Folders v;
Crash's Tracking & Training (5e) v;
Curse of Strahd v;
Custom Fonts v;
Day Night Cycle v;
D&D 5th Edition PHB Journal Styling v;
Dice So Nice! v;
Dice Tray v;
DnD5 Cheatsheet v;
DnD5e Helpers v;
Drag Ruler v;
Drop Effects on Items v;
FXMaster v;
GM Screen v;
Hurry Up! Combat Timer v;
Lazy Money v;
Let's Trade 5e v;
lib - Color Settings v;
libWrapper v0;
LightsHUD v;
Link Item and Resource DnD5e v;
Long Rest Hit Die Healing for D&D5e v;
Loot Sheet NPC 5e v;
Mob Attack Tool v;
Monk's Active Tile Triggers v;
Monk's Little Details v;
Multiface Tiles v;
Navigation Name v;
Party Overview v;
Perfect Vision v;
Permission Viewer v;
Pings v;
Push Token Back - Reveal Tokens Buried Behind Each Other v;
RPG Styled UI for Foundry VTT v;
Settings Extender v;
Shared Data v;
Simple Calendar v;
socketlib v;
SocketSettings by Blitz v;
Splatter v;
Stream View v;
Super Select v;
Tabletop RPG Music v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Timer v;
Token Magic FX v;
World Explorer v;

**Comment by tagnullde** [comment]
> > 
> 
> is it better roll module ?

I do have it installed. So it could be it.

**Comment by Sasmira** [comment]
> > is it better roll module ?
> 
> I do have it installed. So it could be it.

can you try on a new world with RPG Styled Ui and Better Rolls if you have same result plz ?

**Comment by Sasmira** [comment]
80% of errors in dd5 or conflicts, come from Better Rolls and better rolls + midi qol... it's a guaranteed conflict :D

**Comment by tagnullde** [comment]
Seems to be one of the 20% conflicts then.
Only better rolls and rpg-ui are active. Still the crit question is near the chat and easily missed on a 2k monitor. ;)

![image](https://user-images.githubusercontent.com/44159008/151703423-72700673-d7d4-4095-8f74-18549c56371f.png)

**Comment by Sasmira** [comment]
I understand your problem :D
your problem is that window pop all time in same location, just below the result window  :D
 
<img src="https://puu.sh/IFVGg/10b3673ea5.png">

but it's not a problem of RPG Styled Ui ... you need to create an issue  here but I think it is intended by the author
https://github.com/RedReign/FoundryVTT-BetterRolls5e/tree/master/betterrolls5e

**Comment by tagnullde** [comment]
Roger :)
