### ISSUE TITLE
Bug with whole UI

### ISSUE THREAD

**Issue by remiverdel** [Xbozon/rpg-styled-ui#36]
Hi,

I tried to use your UI because I really love the design but when I launch my game, the chat part gets replicated on the whole screen.

<img width="2528" alt="Capture d’écran 2022-01-03 à 16 01 06" src="https://user-images.githubusercontent.com/22896375/147946331-22772d1b-3081-4d51-b7c8-c68793cc2af5.png">

By the way, I have no other module activated.

**Comment by Xbozon** [comment]
@remiverdel Please update to v7.0.0

**Comment by remiverdel** [comment]
The module or Foundry update? I have the latest V9 foundry version
