### ISSUE TITLE
Module compatibility and override issue and Combat carousel

### ISSUE THREAD

**Issue by remiverdel** [Xbozon/rpg-styled-ui#37]
Hi,

Now that I got the module working, I was wondering if it was compatible with Minimal UI because there seem to be some strange dispositions going on. My macro bar is all the way to the right, the player list also is a bit to the right and not really in the corder. Also, the pause menu logo seems to be overridden as I selected a custom one in Minimal UI. Same for the Foundry logo in the corner. In Minimal UI and your module I disabled it, but the navigation stays to the right instead of taking the vacant place. Is it a compatibility issue?
<img width="720" alt="Capture d’écran 2022-01-03 à 16 22 18" src="https://user-images.githubusercontent.com/22896375/147948302-2311aa1f-dbd5-4ff1-987d-666648fed387.png">

Also, about Combat Carousel, love the new design of the UI but I just saw that it's not possible anymore to roll initiative from the red dice button that was on the token image. Now we have to either go into the combat tracker menu to roll initiative or to input it manually.

**Comment by Xbozon** [comment]
@remiverdel 
It takes time to understand the problem

**Comment by remiverdel** [comment]
Sure I get it. Don't worry all of those are really minor problems, they are really aren't game breaking or anything. Would just love to see all those modules seamlessly blend together, would be absolutely perfect for immersion and efficiency!

Cheers

**Comment by Sasmira** [comment]
> 

Hello for your minimal ui, you can use standard mode for logo and adjust in manual the pixel position for your Macro bar. All is in minimal ui setting :D

<img src="https://puu.sh/IAzL1/735b5e8e59.png">
