### ISSUE TITLE
CSS makes journal notes hard to read

### ISSUE THREAD

**Issue by tagnullde** [Xbozon/rpg-styled-ui#38]
Not 100% sure if it's your CSS. But headings and inline objects are white and hard to read.

![image](https://user-images.githubusercontent.com/44159008/147986189-09c826dd-aad3-45d2-8d61-bf15a519025b.png)

**Comment by Xbozon** [comment]
@tagnullde 
Is this on the latest version of the mod? I think I already fixed it, but maybe something has changed in v9.

**Comment by tagnullde** [comment]
Seems to be fixed. I don't have the issue anymore.

**Comment by Xbozon** [comment]
@tagnullde 
Thanks for writing!) Apparently the update foundry
