### ISSUE TITLE
Chat background doesn´t support sidebar resizing

### ISSUE THREAD

**Issue by HumanWreck** [Xbozon/rpg-styled-ui#39]
Hi Xbozon, 

your UI is something I was looking for a looong time. Amazing and very well suited for my DnD Ravenloft campaigns. 

There is one thing I would really love to see tweaked and it is the background image of chat window. If you resize the chat via modules available for FVTT (f. e. Sidebar and Chat Resizing), the background is getting "repeated" instead of "extended", which creates a white gap between repeated backgrounds. In our group, we play only via chat (no V/C) and resizing is almost mandatory to avoid missing messages. But sometimes, it is difficult to read messages because of that white "gap". 

Another really minor thing is a compatibility with Minimal UI module. It works pretty fine, the only thing which is not optimal, is behavior of macro/shortcut bar. In case of your UI, it is not possible to move the macro bar to the left/right with Minimal UI configuration. It stays in the center, regardless of the config, and it overlaps with my favourite Monk´s TokenBar. Currently, I use Auto-Hide, but maybe it is just and easy fix, so... ,) Other parts of the UI are configurable with Minimal UI just fine. 

Thanks for your amazing job!

![RPG UI resize PrtSc](https://user-images.githubusercontent.com/72232643/148431643-ecf4e159-2a3e-423a-81f2-d3eb46bbb8b5.png)

**Comment by Xbozon** [comment]
@HumanWreck 
Put the chat in stretch mode. As for the hotbar, changing its behavior based on minimal ui is problematic. If this is important, please create another issue.
