### ISSUE TITLE
Remove the Foundry VTT Label

### ISSUE THREAD

**Issue by giogreymon** [Xbozon/rpg-styled-ui#4]
If it is possible to remove the Foundry VTT Label in the Top-Left corner. or at the very least have it be default with the Logo

**Comment by giogreymon** [comment]
I have a smaller screen and it is Huge on mine.

**Comment by Xbozon** [comment]
Do you remove the standard logo as well? Or is the standard logo smaller and doesn't take up space?
It's not hard to remove, but a screenshot would help to understand the problem.

**Comment by giogreymon** [comment]
![image](https://user-images.githubusercontent.com/77355668/122017269-d2778e00-cd8f-11eb-9776-fe2bc64c8089.png)

Yes if its possible to remove it and just have it be a blank space. The standard logo *is* smaller, but still take up space.

**Comment by Xbozon** [comment]
Got it. I'll add it as a settings option. 

Yes, my version of combat carousel was geared for square images, I missed the other sizes, I'll try to fix that too.
We use the tokenizer to have separate images for the tracker and the token. The left one will be used in the tracker, the right one as a token.
https://foundryvtt.com/packages/vtta-tokenizer/d

 Thank you! It makes me happy every time I see people using it.

**Comment by Xbozon** [comment]
![image](https://user-images.githubusercontent.com/5074477/123509379-cd62ea80-d67d-11eb-8519-439395d9a53b.png)

I've added compact mode to the settings and made some adjustments to the image handling. Squares will work best, but other sizes at least look acceptable.
