### ISSUE TITLE
Scene navigation wraps to late

### ISSUE THREAD

**Issue by tagnullde** [Xbozon/rpg-styled-ui#40]
The scene is behind the right menu. Would be nice if it would wrap earlier. Thanks.

![image](https://user-images.githubusercontent.com/44159008/149983814-cd5e4d80-88e9-42be-81d4-6a69d46b766c.png)

**Comment by Sasmira** [comment]
Hello @tagnullde
change this line 
```java
#navigation {
    left: 142px;
}
```
by this line
```java
#navigation {
    width: calc(100% - 340px);
    left: 142px;
}
```

**Comment by tagnullde** [comment]
> Hello @tagnullde change this line
> 
> ```java
> #navigation {
>     left: 142px;
> }
> ```
> 
> by this line
> 
> ```java
> #navigation {
>     width: calc(100% - 340px);
>     left: 142px;
> }
> ```

That fixed it for the time being for me. Thanks.
Would be great if it will become a feature. Since it would be removed once the module updates.

**Comment by Xbozon** [comment]
@tagnullde 
I'll add it in the next update. It's very difficult to release them right now, there's a lot of stuff IRL.

**Comment by tagnullde** [comment]
i feel you. don't worry about it.

**Comment by Xbozon** [comment]
@tagnullde Fixed in @Sasmira Merge request. Please update to v0.7.2.
