### ISSUE TITLE
Dropdown controls for Monk's Enhanced Journal are being disabled

### ISSUE THREAD

**Issue by GrumpyVader** [Xbozon/rpg-styled-ui#45]
While doing some testing with Monk's Active Journal I found that some dropdown controls he implements on the forms are being disabled by the UI. Monk tracked down the CSS line.

css line 896 .journal-sheet form select should be changed to .journal-sheet form select[name="folder"]

**Comment by Xbozon** [comment]
@GrumpyVader Hello, a screenshot would help solve the problem faster, thanks!

**Comment by GrumpyVader** [comment]
Sure thing. Here you go.

With RPG Styled UI disabled:
![image](https://user-images.githubusercontent.com/39166319/152226306-f171f890-a5b8-4946-b9fc-9dc46573b0e6.png)

With RPG Styled UI enabled:
![image](https://user-images.githubusercontent.com/39166319/152226589-163f7ce6-30fd-4f1e-bf6e-3097d97547b2.png)

**Comment by GrumpyVader** [comment]
here is one for a Shop type journal sheet.

RPGSU disabled:
![image](https://user-images.githubusercontent.com/39166319/152227712-15049dbd-5dbf-4f30-aeb4-d05950677397.png)

RPGSU enabled:
![image](https://user-images.githubusercontent.com/39166319/152228179-0e4aa9e7-9e9d-4909-bec5-767ef470904c.png)

**Comment by Xbozon** [comment]
@GrumpyVader Got it, thanks!

**Comment by Xbozon** [comment]
@GrumpyVader Fixed in v0.7.6. Thanks!
