### ISSUE TITLE
Navigation bar disapear

### ISSUE THREAD

**Issue by Cimeryl** [Xbozon/rpg-styled-ui#46]
Conflict between Rpg Style UI and Minimal UI
When both are active, my navigation bar disapear. 

With Minimal ui : 
![image](https://user-images.githubusercontent.com/73182114/152147336-b5f69d21-1428-4712-ab01-69425ed08f00.png)

Without Minimal ui : 
![image](https://user-images.githubusercontent.com/73182114/152147455-353150fb-c707-4c98-a26d-c8b9f289d40f.png)

**Comment by Xbozon** [comment]
@Cimeryl Fixed in v0.7.5
