### ISSUE TITLE
Rolltable text description.

### ISSUE THREAD

**Issue by Padhiver** [Xbozon/rpg-styled-ui#48]
Hello,
I'd like to point out a small bug. When we launch a random table, the descriptive text is very (too?) dark, it's almost unreadable. :)

![image](https://user-images.githubusercontent.com/80126915/152694161-eafaf949-e138-4cfc-8211-a1f195ccb7a5.png)
![image](https://user-images.githubusercontent.com/80126915/152694257-a2d06c89-e0d8-4bb5-a589-d199ca2ca42b.png)

"This is a test sentence"

Thank you !

**Comment by Xbozon** [comment]
@Padhiver Sorry for the wait, fixed in version 0.7.7
