### ISSUE TITLE
Incompatibility with Combat Carousel 2.1

### ISSUE THREAD

**Issue by coolfox09** [Xbozon/rpg-styled-ui#5]
Hi! Loving the module and all my players have been obsessed with it. However, Combat Carousel just updated to 2.1 and it breaks with this module as the alignment is off for the hp and initiative count and it moves to the left. Luckily I can revert back to an older version of Combat Carousel but hope you can fix this at your earliest convenience!

**Comment by Xbozon** [comment]
@coolfox09 

I was really looking forward to this release too. Lately, Combat Carousel has had a few bugs in the works. I'll be working on an update soon, expect it Friday-Saturday!

**Comment by coolfox09** [comment]
Hi Xbozon, thanks for all the hard work as always! 

As you can see in this screenshot this is what the Carousel looks like with the new update on your dark skin. This applies whether if collapsed or not: 

![image](https://user-images.githubusercontent.com/3613208/124813672-015dcb80-df1a-11eb-9528-a5cd64812b11.png)

And this is what it's intended to look like if i have your skin turned off: 

![image](https://user-images.githubusercontent.com/3613208/124813998-56014680-df1a-11eb-8853-4475c1e53172.png)

As you can see, with the skin on, the alignment of the overlay is all the way to the left and I'm unable to click and drag to move it. Even then, the alignment of the HP bar and Name is out. And now with Combat Carousel 2.1, there are options to scale down the UI and also scale up the UI that is automatic without your skin, but with your skin, the images stay the same size despite the UI increasing: 

![image](https://user-images.githubusercontent.com/3613208/124814393-ca3bea00-df1a-11eb-84a8-b7201e8a738d.png)
For Large

![image](https://user-images.githubusercontent.com/3613208/124814496-ec356c80-df1a-11eb-8fc6-49ff7986da9c.png)
For Small

And as you can see in all cases I'm unable to drag it out to move it like how Combat Carousel 2.1 allows. I hope these were helpful! Lemme know if there's any other way I can help :)

**Comment by Xbozon** [comment]
Thanks! Very detailed, it all makes sense to me. I took a first look at the problem. I may not be able to do the health display quickly, but everything else is solvable. I might even be able to add resize support too.

**Comment by Xbozon** [comment]
I've released the initial fix. I'll need more time to stylize the health bar and small issues, but it's already usable!

![image](https://user-images.githubusercontent.com/5074477/125200161-5d09bb00-e272-11eb-8318-b479dc856167.png)

**Comment by Xbozon** [comment]
Unfortunately so far nothing could be done with the health bar, the code generating it is not able to change through css. I will come back to it later in another task.
