### ISSUE TITLE
New problem with version 1.6 of dnd.

### ISSUE THREAD

**Issue by Padhiver** [Xbozon/rpg-styled-ui#53]
![image](https://user-images.githubusercontent.com/80126915/165628999-6e619dfb-399a-40f1-8f69-e1f6ca19c201.png) 
![image](https://user-images.githubusercontent.com/80126915/165629442-bac34887-bedb-4ea9-a731-c77c6949c8f1.png)

Hello !
With the new version of DnD, there is a little problem in the progress window, the links to the abilities are almost unreadable. :)
It's only when you haven't taken the levels yet, if you level up it becomes readable.

That's it! Thanks to you. :)

**Comment by Sasmira** [comment]
je regarderais si je peux faire une correction 🗡️

**Comment by Xbozon** [comment]
I added a fix by @Sasmira, thanks for the help!
