### ISSUE TITLE
Issue with Monk enhanced journal

### ISSUE THREAD

**Issue by Darshyne** [Xbozon/rpg-styled-ui#56]
Hello there is an issue with Monk's enhanced journal : this dropdown menu disappear with RPG-Styled UI
![Capture d’écran 2022-05-06 à 15 10 37](https://user-images.githubusercontent.com/47222495/167138109-645ba884-694d-49c8-af05-04675385e164.png)

**Comment by Xbozon** [comment]
Unfortunately, I just now got to this error and apparently it is no longer relevant. I will close this issue, but if you are still experiencing the problem, reopen it or create a new one. Thank you!
