### ISSUE TITLE
Remove the color: inherit on .discarded

### ISSUE THREAD

**Issue by Gremlinism** [Xbozon/rpg-styled-ui#57]
Hi, love the mod, thanks for the great work you do on it.

Is it possible to remove the color: inherit style on .discarded? When we roll with advantage/disadvantage you can't see the dice result of the discarded roll. Currently the only way to see it is to find it and turn it off in the elements with each roll.

Thanks

Color: Inherit On:
![image_2022-06-02_114324296](https://user-images.githubusercontent.com/106721083/171548672-b84e93b7-2387-4ffa-a8f7-bdb109dd0e25.png)

Color: Inherit Off:
![Inherit off](https://user-images.githubusercontent.com/106721083/171548779-e153fe83-ac4c-4401-90c9-9b2e5f36a6a3.JPG)

**Comment by Sasmira** [comment]
something like this maybe ?
<img src="https://puu.sh/J3BT2/88ad09ec75.png">

**Comment by Gremlinism** [comment]
Yeah, that'd work great, it still highlights the correct roll more but lets us see what the discarded one was

**Comment by Xbozon** [comment]
I added it to the main branch.

Sorry it took me so long, I'm moving and don't have internet :(

**Comment by Gremlinism** [comment]
Oh don't stress at all, we had the workaround. Thanks for all the work on it, appreciate it and the theme always gets comments from our players on how awesome it looks.

**Comment by Sasmira** [comment]
héhé when I know, I can create a little fix !
