### ISSUE TITLE
Some Problems with the german layout

### ISSUE THREAD

**Issue by vt-tom** [Xbozon/rpg-styled-ui#59]
Hey, at first thank you for this cool UI.

I have got some Problem when i use the german DnD module. The NPC Sheet cuts somethink of on the bottom of the sheet. Also one Text is a little bit to big. 

![grafik](https://user-images.githubusercontent.com/80099175/172803556-ec62dc04-b511-4017-864d-ebee27398c2a.png)

**Comment by Sasmira** [comment]
for the title bar, I have same problem in French, and I resolve this problem with a module like https://github.com/MiahNelah/cleaner-sheet-title-bar

for you second problem, have you same problem without RPG Ui ?

**Comment by vt-tom** [comment]
Thanks for the module, this helps me a lot.
And the text "Mit Tieren umgehen" is also without the UI too big. So this will be nothing for you to fix.

But the bottom of the sheet is too short. Here ist the normal sheet:
![grafik](https://user-images.githubusercontent.com/80099175/172812515-a4635498-8f1a-4c36-9377-2b602f84b7fb.png)

**Comment by vt-tom** [comment]
Thank you very much

**Comment by Sasmira** [comment]
I'm not a DnD player but I help my friend xbozon when I can :)

**Comment by Xbozon** [comment]
Thanks for using the mod!
I merge changes from Sasmira.
