### ISSUE TITLE
Incompatible with Illandril's Hotbar Uses

### ISSUE THREAD

**Issue by Methose** [Xbozon/rpg-styled-ui#6]
Hello!

This is my new favorite UI, but the module above does not work with it. 
I like to see all the uses and charges for items, and the changes to the hotbar makes those no longer show up.

**Comment by Xbozon** [comment]
Got it, I'll try to fix it!

**Comment by Xbozon** [comment]
@Methose Fixed, try it!

![image](https://user-images.githubusercontent.com/5074477/126042655-1783aff8-fd53-4a72-998e-bab1a1728213.png)
