### ISSUE TITLE
Version for non-dnd?

### ISSUE THREAD

**Issue by DKtric3L** [Xbozon/rpg-styled-ui#61]
it would be great if you added ui support for not only under dnd5e system.

**Comment by Xbozon** [comment]
Hello, what system do you use?

**Comment by DKtric3L** [comment]
The Witcher TTRPG.

**Comment by Sasmira** [comment]
it's already difficult to have an Ui up to date for one system .... Xbozon work on DD5 and me I'm working on a fork of RPG Styled ui for a PF2e version.
If you want a version for The witcher TTRPG, you can create a fork of RPG Styled ui, it's the best soluce :)

**Comment by Xbozon** [comment]
@DKtric3L 

I thought this through well when I checked the v10 version and decided to remove the restriction on systems, however I will continue to maintain only dnd5e and pathfinder 2.
