### ISSUE TITLE
compatibility warnings V10

### ISSUE THREAD

**Issue by darkmogool** [Xbozon/rpg-styled-ui#66]
Since Foundry V10, I'm getting some issues. Somme minor ones, but issues nonetheless.
I'm on the standalone client on a Windows 10 machine, Foundry V10, build 284, module version 1.0.4

![grafik](https://user-images.githubusercontent.com/51697978/189093633-ac872b81-68ad-46b5-a195-d10591a81151.png)

**Comment by Sasmira** [comment]
Hello Hello, 

you play with a version in v9 ... we work on a new release atm :)

**Comment by darkmogool** [comment]
Hi there,

I mean, it works so far for me. I didn't notice any problems regarding those error messages.
The only strange thing I noticed since the update was the colour (and the size, of which I don't know if the issue is on "your" site) of the new formatting buttons in the journal. The rest was really not a problem since.

![grafik](https://user-images.githubusercontent.com/51697978/189271399-724342c8-e6d0-47ec-92b1-9a88ad0ce891.png)

**Comment by Sasmira** [comment]
The first change in v10 is a new journal version and it's normal if you have a bug with your version ... RPG Styled ui is actually compatible with v9 only :)
the next version that I have PR and Xbozon need verify, will be v10 compatible like on this screenshot

<img src="https://puu.sh/JkqVM/e131d3aa95.jpg">

**Comment by darkmogool** [comment]
Yeah, I already thought this.
It's coming together very nice :D
Thank you for your Work and the Module in general. Foundry looks soooo much better with it 😍

**Comment by Toastghost7** [comment]
Would like to echo my thanks - I literally can't go back to using Foundry WITHOUT this UI lol, it's a night and day difference.
Whenever an update happens, this is always the module I check compatability for first! A must have!

**Comment by Xbozon** [comment]
Thank you so much for your words of encouragement. Sometimes I think my module is used by only 2-3 people, but your words make me think otherwise, I'm glad you found it useful!

Thanks to @Sasmira for helping me upgrade to v10, changes have been added to the main branch.
