### ISSUE TITLE
[Visual Improvement] White text on parchment not ideal

### ISSUE THREAD

**Issue by tagnullde** [Xbozon/rpg-styled-ui#68]
Foundry: 10.286
System: 5e v2.0.3

The readability with the white text on the parchment background is not ideal. Is the a chance to make the text more readable?

![image](https://user-images.githubusercontent.com/44159008/192137083-83079f47-137b-418e-a25b-621dc301937a.png)

Thank you for putting your module out there. It really enhanced my Curse of Strahd Campaign.

**Comment by Sasmira** [comment]
it's an option of Monk's little details ... you need to turn off this option
<img src="https://puu.sh/Jn51F/a6deb075c7.png">

I have PR a new version of RPG Styled UI with Monks little details option turn off by default :)

**Comment by tagnullde** [comment]
That did it. Thanks for the tip. Shall I close this issue?

**Comment by Sasmira** [comment]
you can if it's good  :)

**Comment by tagnullde** [comment]
Well, the white-text is still there.

I'll edit the issue and remove everything solved and let XBozon handle the rest.

**Comment by Toastghost7** [comment]
I'm a bit confused, reading this. I don't even have Monks little details installed and i'm still getting the white text on parchment. Any other suggestions on how to fix it?

**Comment by Sasmira** [comment]
> I'm a bit confused, reading this. I don't even have Monks little details installed and i'm still getting the white text on parchment. Any other suggestions on how to fix it?

Hello Hello,

- Foundry version ?
- DD5 version ?
- Styled ui version ?
- A screenshot maybe to see your problem ? 

S. :)

**Comment by Toastghost7** [comment]
Gladly! Thanks for taking the time.

Foundry version: Version 10, build 291.
D&D5E Version 2.0.3
Styled UI version is on 1.1.0

And it looks like this:
![Example](https://user-images.githubusercontent.com/113179796/211318885-cde6b768-d190-445b-a64b-14026ad3bf79.png)

**Comment by Xbozon** [comment]
@Toastghost7 

I plan to release a patch this coming weekend (I'm already working on it). It will include a fix for this problem.

Thanks for the additional screenshots!

P.S.
@Sasmira I'll take your list of questions for the Issue template :)

**Comment by Toastghost7** [comment]
Great to hear! Looking forward to it.
Thanks for the hard work, as always!

**Comment by Xbozon** [comment]
@Toastghost7 
I fixed this in v1.1.1, try it!

**Comment by Toastghost7** [comment]
@Xbozon 

Thanks so much! Looks really good, much more readable. My only critique would be, heading 2 under heading 1 looks a little worse now, it looks like everything is highlighted all at once, if that makes sense. Might be nicer if only Heading 1 glows with a red border, like with this quick example I made. Left is how it currently looks, right is a rough example of how it might look without the glow on heading 2.

![SCuffed_Example](https://user-images.githubusercontent.com/113179796/212933497-077af1c0-a946-4e4d-9655-81a7768c90a9.png)

**Comment by Xbozon** [comment]
@tagnullde 
Yes, it's a bug, it's strange that I didn't find it. I'll try to fix it soon.

**Comment by Bernie-McGee** [comment]
Should this be reopened for chat readability? Or should I submit a new issue?

![readability](https://github.com/Xbozon/rpg-styled-ui/assets/43075380/02c9df50-4e35-4aca-8937-adf2cffe0c5e)

**Comment by Sasmira** [comment]
Hello Hello,
- which dnd version ?
- Have you try without modules ?
- What's the name of your module with an B icon ?

**Comment by Bernie-McGee** [comment]
Weird, I could swear I responded the other night. But it was super late, maybe I forgot to submit the comment. Sorry for the delay!!

- 3.0.1
- Yes, I made a clean testing world with only RPG Styled UI enabled. The problem still exists.
- (Beyond20)

**Comment by Sasmira** [comment]
no worries, it happens to the best of us too :D
I'll see on my side as soon as possible, but I can't guarantee anything ... I don't play DD5 but I do a bit of maintenance on the ui.

**Comment by Xbozon** [comment]
I'm here too, but won't be able to take over in the next week :(

**Comment by Sasmira** [comment]
> I'm here too, but won't be able to fix it in the next week :(

he is alive :D

**Comment by Bernie-McGee** [comment]
No problem, I have a workaround using Lib Themer. 

Thanks for the amazing theme (for free to boot!).

If there's anything I can do to help testing wise, let me know. Happy to help.

**Comment by Sasmira** [comment]
> No problem, I have a workaround using Lib Themer.
> 
> Thanks for the amazing theme (for free to boot!).
> 
> If there's anything I can do to help testing wise, let me know. Happy to help.

I send you a MP on discord if you want expose me your problems

**Comment by Sasmira** [comment]
ok PR done 
https://github.com/Xbozon/rpg-styled-ui/pull/91
