### ISSUE TITLE
Color properties for level up button

### ISSUE THREAD

**Issue by GCSmith-07** [Xbozon/rpg-styled-ui#69]
The auto leveler button (which is default black) only shows up on the sheet as a white border box making it hard to tell the purpose of the box. 
![image](https://user-images.githubusercontent.com/100705086/194619348-c2eba8fc-446e-4568-800d-a871a4aa769a.png)

Otherwise, love the look and feel of everything. Looks great!

**Comment by Xbozon** [comment]
I apologize for the long reply. I tried looking for this button, but it doesn't show up for me. Is this some kind of plugin?
