### ISSUE TITLE
Request to retain intact left-side menu and Foundry menu

### ISSUE THREAD

**Issue by sashemi** [Xbozon/rpg-styled-ui#7]
Hello,

Thank you so much for developing this module. As someone who has extreme photophobia due to damaged irises, I appreciate the dark colored UI I can use, which is otherwise not possible with Foundry.

I was filing this request so that an option could be included to leave the left-hand side menu intact, along with the Foundry logo (dice and anvil). I like its appearance, as I'm fond of the product, and would like to continue seeing its logo as I run my games.

Thanks for reading!

**Comment by Xbozon** [comment]
@sashemi 

I originally thought long and hard about the decision to change the standard logo, but I did it to match the style. Anyway, I've been thinking about the option of returning the standard logo myself, and I'll do it for sure.

Tell me, is there any difficulty with the left menu? The standard design isn't very pretty.

It's not hard to do, just please tell me the reasons :)

P.S.
Take care of your eyes!

**Comment by sashemi** [comment]
Hi there,

Thanks for your response!

For the left-hand side menu, I am sorry to have lumped it in. I do appreciate all the work you've done.

Here were 2 issues with it - see below default:
![image](https://user-images.githubusercontent.com/67514037/125899817-c2687336-ddad-411a-8f30-9134c725cb52.png)
1, The icons are a bit farther apart than the default layout. I don't think this necessarily adds any functionality or conformance to rest of your UI
2. There was no visual indicator (like the orange box) for what is currently selected

The same left-hand side menu with your extension (first two icons are active - but not visually apparent):
![image](https://user-images.githubusercontent.com/67514037/125900068-3eaa4d42-c733-4f84-8158-3c578bf92bd5.png)

Thank you!

**Comment by Xbozon** [comment]
@sashemi 

Let me make them closer to each other and accentuate the active icons, if that doesn't help, add an option to revert to the classic menu.

(actually the icon itself gets a little lighter if active, but I think it may not be visible due to vision or monitor, glad you wrote about it, I'll fix it!)

**Comment by sashemi** [comment]
I see the slight accent now that you mention it. It is white instead of the subtle dark red/brown. I would have never noticed until you pointed it out! You don't have to accommodate it.. my contrast vision is unfortunately quite kaput.. but if you made it more noticeable that would be amazing. Thank you!

**Comment by Xbozon** [comment]
@sashemi 

Alpha 0.3.1

- Added support for Illandril's Hotbar Uses
- Possibility to return the standard logo
- Brighter highlighting of the active menu

Please tell me if you are still experiencing difficulties.
