### ISSUE TITLE
[Compatability] Column alignment fix for Monk's Hotbar Expansion

### ISSUE THREAD

**Issue by hoyer1066** [Xbozon/rpg-styled-ui#71]
Monk's Hotbar Expansion lets you show all 5 of the hotbar rows at the same time.

As it stands, it is not effected by this module and therefore the expanded rows are shorter and unaligned with the effected main hotbar row. Compatibility would be just a simple inclusion of the spacing to these expanded rows.
![Hotbar](https://user-images.githubusercontent.com/77966438/199434110-9558dded-edce-465a-afa4-a21d4bd349f4.JPG)

**Comment by Xbozon** [comment]
@hoyer1066 
I fixed this in v1.1.1, try it!

![Снимок экрана 2023-01-15 141117](https://user-images.githubusercontent.com/5074477/212524278-ec4f1e89-7f5f-4535-8417-b974da2d7667.jpg)

**Comment by hoyer1066** [comment]
works perfectly!
