### ISSUE TITLE
v11 - initial compatibility looks good.

### ISSUE THREAD

**Issue by tehguitarist** [Xbozon/rpg-styled-ui#76]
Just thought I'd leave a note that initial compatibility looks good for v11. I also applied the fixes Sasmira has in the open PR, and all seems to be working smoothly so far. All I did was up the maximum compatibility to 11.

**Comment by darkanx** [comment]
This is, without a doubt, my favorite ui mod. I got some css updates I'll try to submit (basic tidy sheet theming and some compatibility edits with other modules) but not sure if the author is still managing this one. Considering making a fork, but I'm still pretty much a noob at the Javascript side of things. Anyone else thinking of taking up the mantle?

**Comment by Xbozon** [comment]
good afternoon, can you explain a little what needs to be done?  I tested the mod on version 11, it worked.

**Comment by darkanx** [comment]
Oh, sorry, didn't mean to confuse you, module works fine in v11. I just meant I might have some css contributions, but wasn't sure if they would get cleared to be added to the master since there were some commits that had never been pulled in... I am still figuring out the whole github thing, very new to me, but will see about getting those contributed sometime!

**Comment by Xbozon** [comment]
Now I understand.  I'll be happy to review your changes if you create a pull request, thanks for using the module :)

**Comment by Sasmira** [comment]
> Hello, can you explain a little what needs to be done? I tested the mod on version 11, it worked.

Hello Hello,

I'm also working on updating the interface and I've found a small problem. When switching to v11, the whole interface seems to have moved up 10px more or less. You can see it when you see the space under the shortcut bar :)

<img src="https://puu.sh/JLZBG/760fe192a0.jpg">
<img src="https://puu.sh/JLZCo/dcd818df8b.png">

**Comment by Sasmira** [comment]
ok fixed :D

**Comment by darkanx** [comment]
Oddly, that little problem only seems to happen to some people. The bar is shifted up for 1 of my 5 players, but for no one else.

**Comment by Sasmira** [comment]
> Oddly, that little problem only seems to happen to some people. The bar is shifted up for 1 of my 5 players, but for no one else.

maybe it's just a problem that only appears with certain browsers ... A user pointed out the problem to me and I have exactly this problem on my browser too, although I use Vivaldi and Firefox for my part :D

**Comment by darkanx** [comment]
Maybe, I can poll my players to see what they use. I use Opera GX and have seen no issues on it. I think the player that was seeing the issue was using Chrome. 

There is a module called Custom CSS https://github.com/cswendrowski/FoundryVTT-Custom-CSS that lets you both add global css and user-specific css overrides, if you need to implement the fix on a per-browser basis until it really gets figured out (tho the module just stopped working this last foundry update, unless you delete a portion of the module.json as noted here: https://github.com/cswendrowski/FoundryVTT-Custom-CSS/issues/23#issuecomment-1646560646 )

**Comment by Xbozon** [comment]
This is a very strange bug, it is completely non-existent for me. I use both Vivaldi and Chrome.

Negative margin solves the problem, but wouldn't that move the interface for everyone who didn't have it originally?

**Comment by Sasmira** [comment]
> This is a very strange bug, it is completely non-existent for me. I use both Vivaldi and Chrome.
> 
> Negative margin solves the problem, but wouldn't that move the interface for everyone who didn't have it originally?

I don't know since I have the problem on my side :D

**Comment by MelleStarke** [comment]
> This is, without a doubt, my favorite ui mod. I got some css updates I'll try to submit (basic tidy sheet theming and some compatibility edits with other modules) but not sure if the author is still managing this one. Considering making a fork, but I'm still pretty much a noob at the Javascript side of things. Anyone else thinking of taking up the mantle?

Heyo, I was wondering if you have those fixes yet ready. The Tidy5e character sheets are semi-transparent for me, so I was hoping your edits would fix that.
Cheers!

**Comment by darkanx** [comment]
> > This is, without a doubt, my favorite ui mod. I got some css updates I'll try to submit (basic tidy sheet theming and some compatibility edits with other modules) but not sure if the author is still managing this one. Considering making a fork, but I'm still pretty much a noob at the Javascript side of things. Anyone else thinking of taking up the mantle?
> 
> Heyo, I was wondering if you have those fixes yet ready. The Tidy5e character sheets are semi-transparent for me, so I was hoping your edits would fix that. Cheers!

Xbozon had already rolled them in with the last update a few days ago. Shoud look like this: 
https://i.imgur.com/vhQSsiS.png with only slight transparency. If its more transparent than that, let me know, I probably need to go in and tag some css as important to make sure other modules are not overwriting it. If you just don't like any transparency at all, I can tell you how to disable it easy-peasy with a lil css edit.

**Comment by darkanx** [comment]
> > This is, without a doubt, my favorite ui mod. I got some css updates I'll try to submit (basic tidy sheet theming and some compatibility edits with other modules) but not sure if the author is still managing this one. Considering making a fork, but I'm still pretty much a noob at the Javascript side of things. Anyone else thinking of taking up the mantle?
> 
> Heyo, I was wondering if you have those fixes yet ready. The Tidy5e character sheets are semi-transparent for me, so I was hoping your edits would fix that. Cheers!

Oh, I think I know whats up. I kind of forgot all about tidysheet's light mode. The changes I made are meant to work with dark mode. You can change that in settings>tidy5e sheet>Tidy5e color theme>dark. I will get that issue fixed up.

**Comment by darkanx** [comment]
Just submitted those fixes and improved a lot of things with the Tidy5e style while I was at it (Tidy5e still needs to be put in dark mode). Hope that fixes the issues!

**Comment by Sasmira** [comment]
> Just submitted those fixes and improved a lot of things with the Tidy5e style while I was at it (Tidy5e still needs to be put in dark mode). Hope that fixes the issues!

are you on discord ? it's more simple for speak :D

**Comment by darkanx** [comment]
> > Just submitted those fixes and improved a lot of things with the Tidy5e style while I was at it (Tidy5e still needs to be put in dark mode). Hope that fixes the issues!
> 
> are you on discord ? it's more simple for speak :D

I am. I am .glavier on discord. If you are just wanting to snag my fixes, download this file: https://github.com/darkanx/rpg-styled-ui/blob/main/css/rpg-ui.css (download raw file button) and replace the one in C:\Users\-user-\AppData\Local\FoundryVTT\Data\modules\rpg-styled-ui\css with it.
