### ISSUE TITLE
Compatibility issue with TheRipper's "Mastercrafted" module.

### ISSUE THREAD

**Issue by rotmos70** [Xbozon/rpg-styled-ui#83]
![image](https://github.com/Xbozon/rpg-styled-ui/assets/8523703/acc4c00c-a44e-46da-9238-4e09d36ff651)
There's an issue with the CSS being used in the "journal" for Mastercrafted causing it to become really hard to read, been trying to fix it myself but to no avail, hope you can find a solution for this!

**Comment by Sasmira** [comment]
Hello Hello
Can you add the url of the module plz. I cant find it in the foundry browser ...

**Comment by rotmos70** [comment]
Ah right, of course, that makes sense, it's a premium module from TheRipper93.
https://wiki.theripper93.com/premium/mastercrafted

I could try working this out over with you on Discord if you'd like? If so, my handle is: stribak

**Comment by darkanx** [comment]
I already added compatibility, I am just waiting for my changed to be rolled into the main branch. You can replace the rpg-ui.css file with my version here for those updates: https://github.com/darkanx/rpg-styled-ui/blob/main/css/rpg-ui.css

**Comment by rotmos70** [comment]
Oh thank you so much for your work.
What needed to be changed anyways?

**Comment by darkanx** [comment]
> Oh thank you so much for your work. What needed to be changed anyways?

Nothing fancy on that one, really just three lines of css to make the text and lines dark. Easy peasy.  I have been adding theming for a bunch of things, so if you see anything else that needs some, just let me know.

**Comment by Xbozon** [comment]
Changes have been made, thanks to all participants!
