### ISSUE TITLE
v11 - Bug - entire interface shifts upwards

### ISSUE THREAD

**Issue by Sasmira** [Xbozon/rpg-styled-ui#84]
**First problem** 
- Create a new World
- Add players to the game, more than 5 players preferred
- expand the player menu to show all players
<img src="https://puu.sh/JMJSh/77923be51e.png">

- Write a message in the chat and press enter 
- entire interface shifts upwards
<img src="https://puu.sh/JMJSI/f71fbf2bab.png">

- collapse the player menu and the entire interface returns to its original position
<img src="https://puu.sh/JMJTC/1121afef58.png">

- the problem comes from `the code line 799`
- the problem is `position: absolute`

`#players ol::before {
    position: absolute;
    content: " ";
    width: 120%;
    height: 130%;
    background: url(../ui/frames/players_bg_dark.webp);
    background-size: 100% 100%;
    z-index: -1;
    left: -10%;
}`

**Second problem**
<img src="https://puu.sh/JMJTC/1121afef58.png">

- when you collapse the macro bar, the entire interface shifts downwards
<img src="https://puu.sh/JMJVT/1d2701dec5.png">

- when you reactivate the macro bar, the interface does not return to its initial position. You have to write a text in the chat and press enter for the interface to return to its initial position.
- the problem comes from `the code line 453`, `the code line 472` 
- the problem is `position: absolute` 

`#action-bar:not(.collapsed)::before {
    position: absolute;
    z-index: -1;
    content: " ";
    width: 146%;
    bottom: -10px;
    left: -23%;
    height: 85px;
    background-image: url(../ui/frames/action_bar.webp);
    background-size: 100% 85px;
    background-repeat: no-repeat;
}`

`#hotbar #action-bar .macro::before {
    background-image: url(../ui/frames/macro.webp);
    background-size: contain;
    background-repeat: no-repeat;
    position: absolute;
    content: " ";
    width: 61px;
    height: 78px;
    top: -11px;
    left: -9px;
    z-index: 1;
}`

- I think that if we solve these 3 problems, the modification to `line 24` will no longer be necessary. 
- I've managed to fix the first part, but I haven't found the macro bar yet.

**Comment by darkanx** [comment]
I fixed that bug, it will get rolled into the main branch soon. You can grab my updated rpg-ui.css here https://github.com/darkanx/rpg-styled-ui/blob/main/css/rpg-ui.css or just change this section in the rpg-ui.css at line 23 until then: 

/*Fix v11*/
#interface {
    overflow: clip;
}
/*end*/

**Comment by Xbozon** [comment]
Changes have been made to the main thread, many thanks for the bug report. [darkanx](https://github.com/darkanx) thanks for the fix.
