### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by Puoko123** [Xbozon/rpg-styled-ui#85]
libthemer just updated to a new version, and also this module, and... I did nothing wrong, I just updated these modules, and now the theme is just not working. I'm using foundry v11 most recent stable version, with both libthemer and rpg style ui updated. It was working fine on the last version before the updates

**Comment by Sasmira** [comment]
Hello Hello, 
A PR has been create for this problem
 you can change this line : https://github.com/Xbozon/rpg-styled-ui/blob/48c1a28006437e5aefa27b73290676c6013a612f/scripts/rpg-ui.js#L115

by :  [`// mainCss.setAttribute("href", "modules/rpg-styled-ui/css/compatibility.css")`](https://github.com/Sasmira/rpg-styled-ui/blob/4340691d049d3efe8931a2c5a938be84fa8485ff/scripts/rpg-ui.js#L117)

**Comment by Xbozon** [comment]
Yeah, my mistake. I did not correctly add a new file to support compatibility with other modules. I have released a fix in version 1.1.4.
