### ISSUE TITLE
Firefox issue with the Webcam Dock.

### ISSUE THREAD

**Issue by Sasmira** [Xbozon/rpg-styled-ui#87]
Hello Hello, 

this problem is only with Firefox and work fine with a Chrome like.
problem easy to reproduce, only just with the RPG Styled Ui module actived.

when you activate the cam dock on the top or bottom of the foundry window and fill the chat with messages, the last messages at the bottom push the macro bar and the chat writing area out of the window.
<img src="https://puu.sh/JQqJq/68603e0197.jpg">
<img src="https://puu.sh/JQqJC/3ca87d291c.jpg">
<img src="https://puu.sh/JQqJM/17d860ec27.jpg">

if anyone can find a solution to this problem, because it's beyond my area of knowledge here.

S.

**Comment by Xbozon** [comment]
I'll try to get it resolved this weekend

**Comment by Sasmira** [comment]
Hello Hello,

it seems that if we remove the old fix in the first version of v11, the problem disappears.

line 23-27
```CSS
/*Fix v11*/
#interface {
	overflow: clip;
}
/*end*/
```

**Comment by Xbozon** [comment]
@Sasmira I've made the changes. Thank you for the report.
