### ISSUE TITLE
UI Misalignment

### ISSUE THREAD

**Issue by TheNittles** [Xbozon/rpg-styled-ui#88]
I saw there was a comment about this in another thread, but just wanted to say I'm still having this issue: The UI is aligned a bit too high for me, making the hotbar float about 10 pixels off the bottom of the browser window. I'm using Google Chrome. Image attached.

![image](https://github.com/Xbozon/rpg-styled-ui/assets/137443034/4bd2858f-46da-4b0e-8e2e-f6f48d3017fd)

**Comment by TheNittles** [comment]
Quick Update: Restoring down the window then re-maximizing it to full screen fixes the bug until it the page is refreshed.

**Comment by Sasmira** [comment]
> Quick Update: Restoring down the window then re-maximizing it to full screen fixes the bug until it the page is refreshed.

Hello Hello, we know the problem and we try to resolve it.

In rpg-styled-ui/css repertory, edit the file rpg-ui.css and add the code below.

```
/*Fix v11*/
#interface {
    overflow: clip;
}
/*end*/
```
<img src="https://puu.sh/JRiI8/71a297cfc5.png">

this is a temporary fix that will allow you to use the interface while we look for a better solution.

**Comment by Xbozon** [comment]
@TheNittles Finally this bug is over. Please update to v1.1.7
