### ISSUE TITLE
[Shadowdark] Unreadable popup window for attack/spellcast

### ISSUE THREAD

**Issue by stickas** [Xbozon/rpg-styled-ui#89]
On the Shadowdark system, when you try to attack/cast spell, you get this popup window that let's you change some things (add bonus, use some talents like backstab for thief, etc.). The letters are unreadable due to them being black in a really dark background.

![image](https://github.com/Xbozon/rpg-styled-ui/assets/41856855/3b771528-2f51-422b-a015-3b597b250cda)

**Comment by Sasmira** [comment]
> On the Shadowdark system, when you try to attack/cast spell, you get this popup window that let's you change some things (add bonus, use some talents like backstab for thief, etc.). The letters are unreadable due to them being black in a really dark background.
> 
> ![image](https://user-images.githubusercontent.com/41856855/279368037-3b771528-2f51-422b-a015-3b597b250cda.png)

Hello Hello, 
you use modules that modify the interface?
Do you have the same problem without modules?

**Comment by stickas** [comment]
I do, but I tried disabling everything and leaving only this module and it still is dark as shown on the picture.

**Comment by Sasmira** [comment]
> I do, but I tried disabling everything and leaving only this module and it still is dark as shown on the picture.

I don't play on DD5, I don't know how to get the same window as you ...
when I press on the item to roll an attack, my window is fine 
<img src="https://puu.sh/JTxrW/e3f304b7da.png">

**Comment by stickas** [comment]
If by DD5, you mean Dungeons & Dragons 5th edition, I am not playing on that system. I'm playing on the Shadowdark one, which is a newer system, bridging D&D 5e with OSR systems.

**Comment by Sasmira** [comment]
> If by DD5, you mean Dungeons & Dragons 5th edition, I am not playing on that system. I'm playing on the Shadowdark one, which is a newer system, bridging D&D 5e with OSR systems.

hoo ok let me see if I can check that with this information :D

**Comment by Xbozon** [comment]
@stickas The fix suggested by @Sasmira  has been added. Thank you all!
