### ISSUE TITLE
Chat tabs

### ISSUE THREAD

**Issue by InnilToo** [Xbozon/rpg-styled-ui#9]
Some modules create several tabs in Chat Lag, for example module [Damage Log](https://github.com/cs96and/FoundryVTT-damage-log). Currently it looks out of place.
![image](https://user-images.githubusercontent.com/33260912/135068556-e16e6c53-6963-493a-975d-9c2463bd4342.png)

**Comment by Xbozon** [comment]
@InnilToo 
Unfortunately, need to deal with each specific mod, because there is no universal solution. I'll add a fix for Damage Log.

**Comment by InnilToo** [comment]
Thank you. I hoped this would be universal do it once and have peace of mind forever. 😢

Another module that might need the compatibility care (I am not using but I bet others do) is [Tabbed Chatlog](https://github.com/cswendrowski/FoundryVTT-Tabbed-Chatlog).

**Comment by Xbozon** [comment]
@InnilToo Damage Log compatibility done in v0.4.2. Tabbed Chatlog in progress.

**Comment by InnilToo** [comment]
Thank you!
If I might suggest one more module that could use a bit of love I believe the [Dice Tray](https://gitlab.com/asacolips-projects/foundry-mods/foundry-vtt-dice-calculator) is quite popular.
![image](https://user-images.githubusercontent.com/33260912/135661882-5c3dde97-2924-40fe-91f8-46484c7ac3ba.png)

**Comment by Xbozon** [comment]
I'll add it to my todo :)

**Comment by Xbozon** [comment]
Solved in version 0.4.4
