### ISSUE TITLE
Doesn't show up in modules anymore

### ISSUE THREAD

**Issue by CrysKilljoy** [Xbozon/rpg-styled-ui#97]
It used to work with Frontier Scum and I guess any other system. 
I tested it now on Frontier Scum, Pirate Borg and Fate. Doesn't show up anywhere except for DnD.

**Comment by Xbozon** [comment]
@CrysKilljoy Sasmira is right, unfortunately, it is not possible to submit a module without specifying a particular system. You can add them yourself module.json (or remove all requirements) in the module folder.

If you need instructions on how to do this, please write me.
